=== cris988/criver/listino.dtd
<?xml version="1.0" encoding="UTF-8"?>

	<!ELEMENT Listino	(Azione)+>
	<!ELEMENT Azione	(CodiceAzione, Nome, Prezzo, Disponibilita, Categoria)>
	<!ELEMENT CodiceAzione	(#PCDATA)> 
	<!ELEMENT Nome		(#PCDATA)>
	<!ELEMENT Prezzo	(#PCDATA)>
	<!ELEMENT Disponibilita	(#PCDATA)>
	<!ELEMENT Categoria	(#PCDATA)>

=== cris988/criver/listino.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Listino SYSTEM "listino.dtd">
<Listino>
    <Azione>
        <CodiceAzione>259bc571f703</CodiceAzione>
        <Nome>TitoloB</Nome>
        <Prezzo>2.7</Prezzo>
        <Disponibilita>430</Disponibilita>
        <Categoria>Tecnologici</Categoria>
    </Azione>
    <Azione>
        <CodiceAzione>50f48b9b6a3e</CodiceAzione>
        <Nome>TitoloM</Nome>
        <Prezzo>3</Prezzo>
        <Disponibilita>480</Disponibilita>
        <Categoria>Industriali</Categoria>
    </Azione>
    <Azione>
        <CodiceAzione>250f9ee8e9f9</CodiceAzione>
        <Nome>TitoloN</Nome>
        <Prezzo>3</Prezzo>
        <Disponibilita>300</Disponibilita>
        <Categoria>Tecnologici</Categoria>
    </Azione>
    <Azione>
        <CodiceAzione>cd4fea988b94</CodiceAzione>
        <Nome>TitoloE</Nome>
        <Prezzo>4</Prezzo>
        <Categoria>Alimentari</Categoria>
        <Disponibilita>544</Disponibilita>
    </Azione>
    <Azione>
        <CodiceAzione>08e815f9149f</CodiceAzione>
        <Nome>TitoloC</Nome>
        <Prezzo>2.3</Prezzo>
        <Categoria>Alimentari</Categoria>
        <Disponibilita>500</Disponibilita>
    </Azione>
    <Azione>
        <CodiceAzione>88fec64ef43b</CodiceAzione>
        <Nome>TitoloA</Nome>
        <Prezzo>3.5</Prezzo>
        <Categoria>Alimentari</Categoria>
        <Disponibilita>650</Disponibilita>
    </Azione>
    <Azione>
        <CodiceAzione>c1ad33f91755</CodiceAzione>
        <Nome>TitoloD</Nome>
        <Prezzo>6</Prezzo>
        <Categoria>Alimentari</Categoria>
        <Disponibilita>370</Disponibilita>
    </Azione>
    <Azione>
        <CodiceAzione>4bf1ddd05494</CodiceAzione>
        <Nome>TitoloH</Nome>
        <Prezzo>3.5</Prezzo>
        <Categoria>Alimentari</Categoria>
        <Disponibilita>680</Disponibilita>
    </Azione>
    <Azione>
        <CodiceAzione>20098d01d5c8</CodiceAzione>
        <Nome>TitoloI</Nome>
        <Prezzo>4</Prezzo>
        <Categoria>Industriali</Categoria>
        <Disponibilita>646</Disponibilita>
    </Azione>
    <Azione>
        <CodiceAzione>8877d6c47dc4</CodiceAzione>
        <Nome>TitoloF</Nome>
        <Prezzo>4.5</Prezzo>
        <Categoria>Tecnologici</Categoria>
        <Disponibilita>397</Disponibilita>
    </Azione>
    <Azione>
        <CodiceAzione>9b7701203be0</CodiceAzione>
        <Nome>TitoloZ</Nome>
        <Prezzo>3</Prezzo>
        <Disponibilita>345</Disponibilita>
        <Categoria>Animali</Categoria>
    </Azione>
    <Azione>
        <CodiceAzione>9f828271ae69</CodiceAzione>
        <Nome>TitoloG</Nome>
        <Prezzo>5</Prezzo>
        <Categoria>Industriali</Categoria>
        <Disponibilita>259</Disponibilita>
    </Azione>
</Listino>
